### ISSUE TITLE
Option for satellite images on map

### ISSUE THREAD

**Issue by paulcwatts** [OneBusAway/onebusaway-android#31] opened 2012-08-31 05:32 UTC
This is possible, but I'm not sure if we really need it. If it's easy to do and doesn't get in the way.

**Comment by barbeau** [comment] 2016-05-24 16:55
I'm going to close this as a duplicate of #510, as we can support satellite images on the map as one type of tile provider (and we can support multiple tile providers).

**Closed by barbeau** 2016-05-24 16:55 UTC
Labels: duplicate, enhancement
