### ISSUE TITLE
Google Analytics Data Volume Exceeded Warning

### ISSUE THREAD

**Issue by cagryInside** [OneBusAway/onebusaway-android#336] opened 2015-10-20 03:09 UTC
OneBusAway is getting closer to exceed our free quota for Google Analytics.

OBA submits the application settings information every time the app starts. And, this causes a lot of hits in GA console.

![screen shot 2015-10-19 at 11 01 10 am](https://cloud.githubusercontent.com/assets/2777974/10596848/6e7c3a9e-76b6-11e5-87ae-0a6289ef639c.png)

**Comment by bbodenmiller** [comment] 2015-10-20 06:14
When I was on GA yesterday it said we were already over our limit and would lose data if we do not reduce usage. These items you proposed deleting - are they already collected via custom dimensions?

**Comment by barbeau** [comment] 2015-10-20 12:50
Yes, we're already over our limit - here's the exact text in the GA console:

>Your data volume (125M hits) exceeds the limit of 10M hits per month as outlined in our Terms of Service. If you continue to exceed the limit, you may lose access to future data.

**Comment by barbeau** [comment] 2015-10-20 14:08
The GA console is now reading:

>Your data volume (79M hits) exceeds the limit of 10M hits per month as outlined in our Terms of Service. If you continue to exceed the limit, you may lose access to future data.

I'm not sure if it updated from the change in time window (Sept. 18 to Oct. 18, changed to Sept. 19 to Oct. 19), but if so it would mean that there were 46 million hits on Sept 18th.  Seems like something strange may be going on here, we'll investigate further.

**Comment by cagryInside** [comment] 2015-10-20 15:13
We are submitting only `API Region` as custom dimension. The rest of the items are collected when a user does an action. 
E.g.:
```
ui_action -> button_press -> Set region automatically 
```

**Comment by bbodenmiller** [comment] 2015-10-20 16:28
Based on my calculations here is how things break down:

| Data Type | Hits | 
| ------------- |------------- | 
| iOS events | 29272013 | 
| Android events | 43368427 |
| iOS screens | 13095682 |
| Android screens| 37959946 |
| **Total** | **123696068** |

Which puts us at a cool 114M over the [10M limit](https://developers.google.com/analytics/devguides/collection/analyticsjs/limits-quotas). As you can see even just screen views for one platform puts us over the limit so we likely need to look in to [sampling](https://developers.google.com/analytics/devguides/collection/android/v4/advanced#sampling). Might also need to look in to moving research tracking items to a separate property. Additionally it appears Custom Dimensions do not count towards limit as they are sent as part of other hits so it would be good to move anything we can to that so we can still get these type of metrics (which we could not if #337 and #338 are merged without adding Custom Dimensions):

![image](https://cloud.githubusercontent.com/assets/1192780/10613968/9866dd2c-770c-11e5-94f1-3bdb8b50e28f.png)
![image](https://cloud.githubusercontent.com/assets/1192780/10613973/9fbaa5b8-770c-11e5-8bb1-a4157f3b392e.png)

**Comment by barbeau** [comment] 2015-10-20 21:06
I'm also reaching out to Google Analytics Premium team to get an estimate of cost for switching to paid version.  Costs aren't publicly listed anywhere that I could find - if you see something, let me know.

**Comment by bbodenmiller** [comment] 2015-10-20 23:16
Per [Quora](https://www.quora.com/How-much-does-it-cost-to-have-a-Google-Analytics-Premium-account):
> The licensing fee is $150K if you purchase it directly through Google, but the price is much more variable (+/-), if you purchase it through an authorized reseller.

**Comment by barbeau** [comment] 2015-10-22 13:13
Confirmed by Google:

>annual fee of $150,000 which we invoice monthly ($12,500 per month)

Yeah....

**Comment by barbeau** [comment] 2016-05-27 13:42
Looks like Firebase Analytics may help with this - it provides unlimited reporting on up to 500 distinct events - see https://github.com/OneBusAway/onebusaway-android/issues/501.

**Comment by barbeau** [comment] 2018-08-21 13:46
In the mean-time, we could turn on sampling - see https://github.com/sky-map-team/stardroid/pull/208/files for an example.

**Comment by barbeau** [comment] 2018-10-08 21:38
We now have a deadline of December 3rd, 2018 to resolve this.  Here's the current message in the GA console:

![image](https://user-images.githubusercontent.com/928045/46634976-ca67ea80-cb20-11e8-9876-d62195f65097.png)

The "Learn more" link goes here:
https://support.google.com/analytics/answer/1070983?hl=en&utm_id=ad

Looks like transitioning to Firebase Analytics is our best course of action, which iOS already supports and we have ticketed on Android in https://github.com/OneBusAway/onebusaway-android/issues/501. 

In the short term we will run GA and Firebase Analytics in parallel, and after Dec 3rd we will turn on sampling to keep both analytics platforms active.

**Closed** 2018-12-10 22:55 UTC
Labels: enhancement
