### ISSUE TITLE
Backup option label improvements

### ISSUE THREAD

**Issue by bbodenmiller** [OneBusAway/onebusaway-android#377] opened 2015-11-18 03:02 UTC
I'm seeing some odd things in relation to the backup feature:

* I'm given the option to backup to an SD card but my device does not have or support an SD card
* Clicking the disabled restore from SD card option results in a popup asking if I'm sure
* few days later and the restore from SD card option is now not appearing grayed out

**Comment by barbeau** [comment] 2015-11-18 14:20
Writing to storage on Android has always been tricky as there's been different behaviors on different devices and Android versions.  Some comments inline below.

>I'm given the option to backup to an SD card but my device does not have or support an SD card

We should rename the "SD card" label of the preferences to "storage".  As you say, not all phones have an SD card.  Furthermore, on an LG G4, even though an SD card is available, it writes to internal storage instead.

>Clicking the disabled restore from SD card option results in a popup asking if I'm sure

I can't reproduce this on an LG G4 - when Restore is disabled a tap doesn't do anything.

The restore option should be only be enabled if a) storage is available on the device, AND b) you've previously saved a backup and its available in device storage.

Can you please try deleting the file "/OBABackups/db.backup" in your storage , and try this again?

>few days later and the restore from SD card option is now not appearing grayed out

As mentioned above, the restore option should be enabled after you successfully perform a save.

**Comment by bbodenmiller** [comment] 2015-11-18 16:01
Do we support the [Backup API](http://developer.android.com/training/backup/backupapi.html)? I believe there was also talk before of doing some sort of cloud sync so you could switch between services easily (e.g. Same settings on phone and tablet).

**Comment by barbeau** [comment] 2015-11-18 16:35
We don't currently support the Backup API.  I believe Android 6.0+ should automatically support it, though, although I haven't had a chance to really look into it.  Backup is different from Cloud sync, which is ticketed in #32.  Backup is intended to only be restored to a device when you first log into it, but its not intended to do an ongoing sync of data across devices.  Cloud sync is intended to sync data across devices on an ongoing basis, so, for example, your phone favorites would always match your tablet favorites.

**Comment by bbodenmiller** [comment] 2015-11-18 17:12
It looks like backup API works on many versions of Android where as the new Android 6.0+ backup feature only works if you're running 6.0+ and your apps targets SDK version Android 6.0 (API level 23) and higher.

**Comment by barbeau** [comment] 2015-11-18 17:27
Fixed backup labels in `develop` via https://github.com/OneBusAway/onebusaway-android/commit/075f416790cf4416997ce8671c2b9cee69aac343.

@bbodenmiller I'm going to close this issue - if you can reproduce the tapping on disabled Restore preference giving you a message (vs. not doing anything, which should be the proper behavior), please open a new issue for that specific problem.

**Closed by barbeau** 2015-11-18 17:27 UTC
Labels: enhancement
