### ISSUE TITLE
OBA App crashes when using custom api url

### ISSUE THREAD

**Issue by evansiroky** [OneBusAway/onebusaway-android#649] opened 2016-08-03 23:39 UTC
**Summary:** 

The app crashes if the settings are accessed after setting a custom api url.

**Steps to reproduce:** 

1.  Reinstall app
2.  Go to settings, enter in a custom api url
3.  Exit settings and go to map
4.  Find and click a stop to see arrival times
5.  Go back to the menu and tap "settings"  <-- app crashes here

**Expected behavior:** 

Should go back into settings menu without crashing.

**Observed behavior:** 

App crashed.

**Device and Android version:** 

Make/Model:  LG G3 (LG-D850)
Android version:  6.0

**Comment by themonki** [comment] 2016-08-04 13:04
Maybe this related to #635

**Comment by barbeau** [comment] 2016-08-04 14:10
Thanks @evansiroky! Yes, this is a duplicate of https://github.com/OneBusAway/onebusaway-android/issues/635, so I'm closing.  It's fixed in master branch and I plan to get a new release out early next week.

**Closed by barbeau** 2016-08-04 14:10 UTC
Labels: bug, duplicate

**Comment by barbeau** [comment] 2016-08-10 13:21
This is part of a hotfix in v2.1.2, rolling out to production now.  I also plan to get a new beta out today based on the master branch that will also include this.
