### ISSUE TITLE
ES - OBA icon is clipped when viewing posts

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-android#832] opened 2017-12-22 16:09 UTC
**Summary:** 

When you view ES posts for a stop, the OBA icon is shown in the upper left corner.  It looks like a circular mask is applied, which slightly clips the rounded corners of the OBA icon.  It would be nice if we could remove the clipping, or provide an alternate mask/icon that makes it a complete circle.

Here's a screenshot:

![image](https://user-images.githubusercontent.com/928045/34304621-8395692c-e708-11e7-9c32-c2c7857224e6.png)

@acrown-msft Could you please take a look?

**Steps to reproduce:** 

1. View arrivals for a stop
1. Tap the ES speech bubble icon next to the stop name

**Expected behavior:** 

OBA icon should appear fully without any clipping

**Observed behavior:** 

The corners of the OBA icon are clipped

**Device and Android version:** 

Samsung Galaxy S8+ w/ Android 8.0

**Screenshots:** 

See above

**Comment by amrhossamdev** [comment] 2024-02-28 00:39
I can't reproduce it because I didn't find the posts for a stop @aaronbrethorst

**Comment by neeldoshii** [comment] 2024-03-08 19:58
Can I get assigned to this?

**Comment by aaronbrethorst** [comment] 2024-03-08 21:47
This feature no longer exists.

**Closed by aaronbrethorst** 2024-03-08 21:47 UTC
Labels: bug
