### ISSUE TITLE
Add a preference to disable to GPS warning popup

### ISSUE THREAD

**Issue by paulcwatts** [OneBusAway/onebusaway-android#8] opened 2012-08-26 22:01 UTC
We can add a checkbox for the folks who really don't like this popup.

**Comment by bbodenmiller** [comment] 2017-01-18 06:49
Which warning are we talking about here?

**Comment by barbeau** [comment] 2017-01-18 18:39
It looks like this is a duplicate of https://github.com/OneBusAway/onebusaway-android/issues/697, so I'm going to close this issue in favor of https://github.com/OneBusAway/onebusaway-android/issues/697, which has more specific information.

**Closed by barbeau** 2017-01-18 18:39 UTC
Labels: duplicate, enhancement
