### ISSUE TITLE
Edit text issue in Trip Planner.

### ISSUE THREAD

**Issue by Tejas-67** [OneBusAway/onebusaway-android#1132] opened 2024-02-29 18:11 UTC
**Summary:** 
The current location EditText feild in the Trip Planner page has text set to "Current Location" inititally.

**Steps to reproduce:** 
Click on Plan a trip (beta) option from the drawer on the landing page.

**Expected behavior:** 
their shouldn't be any text in the edittext by default, there should just be a hint. On clicking on the end icon for current location, the actual current location of the user should be fetched and displayed.  

**Observed behavior:** 
the edittext has initital text set to "Current Location"

**Device and Android version:** 
Google Pixel 7 Pro

What make and model device (e.g., Samsung Galaxy S3) did you encounter this on?  What Android version (e.g., Android 4.0 Ice Cream Sandwich) are you running?  Is it the stock version from the manufacturer or a custom ROM?  What version of Google Play Services is running on your device?

**Screenshots:** 
[onebusaway_issue1.webm](https://github.com/OneBusAway/onebusaway-android/assets/110051718/90b46dd0-0558-45a9-9562-3bf48db5f58d)

Can be created by pressing the Volume Down and Power Button at the same time on Android 4.0 and higher.

**Comment by Tejas-67** [comment] 2024-02-29 18:25
@aaronbrethorst please check.

**Comment by HimanshuMahto** [comment] 2024-03-05 09:58
hey there can i work on this.

**Comment by Tejas-67** [comment] 2024-03-05 12:02
@HimanshuMahto I am already working on this.

**Comment by GajananPalepwad** [comment] 2024-03-08 10:15
@aaronbrethorst @Tejas-67  i have solved this issue plz do check

**Comment by barbeau** [comment] 2024-03-08 12:45
I'm pretty sure we don't want to do this, it will break planning from the users real-time location if I recall correctly.

**Comment by GajananPalepwad** [comment] 2024-03-08 13:00
> I'm pretty sure we don't want to do this, it will break planning from the users real-time location if I recall correctly.

Is this for me sir

**Comment by barbeau** [comment] 2024-03-08 16:58
For this issue in general - it's not a bug, it's intended behavior

**Comment by aaronbrethorst** [comment] 2024-03-08 16:59
Closing per @barbeau

**Closed by aaronbrethorst** 2024-03-08 16:59 UTC
