### ISSUE TITLE
Add support for amazon maps api on amazon app store version

### ISSUE THREAD

**Issue by bbodenmiller** [OneBusAway/onebusaway-android#86] opened 2013-10-25 07:36 UTC
Convert app to use [Amazon Maps API](https://developer.amazon.com/sdk/maps.html) when installed on a Kindle Fire. Related to #85.

**Comment by barbeau** [comment] 2015-01-13 18:04
We have a more extensive discussion of this as part of #158, so I'm going to close this as a duplicate of that issue.

**Closed by barbeau** 2015-01-13 18:04 UTC
Labels: duplicate, enhancement
