### ISSUE TITLE
View posted schedule from a stop

### ISSUE THREAD

**Issue by paulcwatts** [OneBusAway/onebusaway-android#16] opened 2012-08-31 04:33 UTC
Move from http://code.google.com/p/seattle-bus-bot/issues/detail?id=17

Reported by project member paulcwatts, Dec 1, 2009
It would be useful to view the posted schedule of departures from the
StopInfo screen.

Right now this information isn't available from the REST APIs, but we could
still link to the KC Metro site for KCM routes.

Comment 3 by hoffman.mm, Jul 19, 2012
Could you link to the OneBusAway web site instead?

Comment 4 by cookieguru, Today (40 minutes ago)
Since this ticket was created an API method has been added:

http://developer.onebusaway.org/modules/onebusaway-application-modules/current/api/where/methods/schedule-for-stop.html

Comment 5 by project member paulcwatts, Today (27 minutes ago)
Yeah, the API has been there for a while. It's just that I haven't had time to implement it :)

Part of the big redesign was to allow for more easily adding functionality like this, so it's potentially possible I could get around to it sooner than later.

**Comment by barbeau** [comment] 2015-09-24 22:48
I'm closing this as a duplicate of https://github.com/OneBusAway/onebusaway-android/issues/82.

**Closed by barbeau** 2015-09-24 22:48 UTC
Labels: duplicate, enhancement
