### ISSUE TITLE
Add trip status/extended arrival details screen

### ISSUE THREAD

**Issue by paulcwatts** [OneBusAway/onebusaway-android#14] opened 2012-08-31 03:45 UTC
This would be useful for three reasons:

1. It's cool
2. we wouldn't have to shove so much into a popup box
3. We could add even more information that would be useful for debugging
4. We could display extra warning text to make it clear when we don't have predicted information. We could finally make people understand what "scheduled arrival" means.

OK, that's four reasons.

**Comment by barbeau** [comment] 2015-09-24 22:50
I believe this is a duplicate of https://github.com/OneBusAway/onebusaway-android/issues/120, so I'm closing as duplicate - if it's not, someone please correct me.

**Closed by barbeau** 2015-09-24 22:50 UTC
Labels: duplicate, enhancement
