### ISSUE TITLE
Show search bar on search results screen

### ISSUE THREAD

**Issue by bbodenmiller** [OneBusAway/onebusaway-android#391] opened 2015-11-30 17:00 UTC
Currently when you do a search you are taken to a new view for the results. If you made a typo or want to update your search query, you must select back and redo the search. Would be great if the search bar remained on the results view.

**Comment by bbodenmiller** [comment] 2015-11-30 17:01
Related to #309.

**Comment by barbeau** [comment] 2015-11-30 20:03
Thanks @bbodenmiller , I'm going to close this as a duplicate of #309 and add your comment to that thread.

**Closed by barbeau** 2015-11-30 20:03 UTC
Labels: duplicate

**Comment by bbodenmiller** [comment] 2015-11-30 21:28
Okay. Just wasn't really sureif  you wanted to have all search improvement ideas in one place since it makes it harder to mark some as complete without marking them as all complete.

**Comment by barbeau** [comment] 2015-11-30 21:50
Yeah, this can be tricky for bigger ticket items like search - I tend to group feedback together early on if I think the implementation will knock off all the items in that thread.  As the implementation solidifies, I may pull out issues that aren't covered by the initial implementation, depending on how that looks.
