### ISSUE TITLE
Clicking "Get google play services" crashes on devices with no market installed

### ISSUE THREAD

**Issue by ssypi** [OneBusAway/onebusaway-android#351] opened 2015-10-30 22:07 UTC
On the `develop` branch:

On devices that have no google play services, there is a button to install them, but if you don't even have market installed on the device, pressing the button crashes the application.

Possible fix: check the intent with [PackageManager#resolveActivity](http://developer.android.com/reference/android/content/pm/PackageManager.html#resolveActivity%28android.content.Intent,%20int%29) before launching it.

~~~
FATAL EXCEPTION: main
    android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=market://details?id=com.google.android.gms&pcampaignid=gcore_8115000--- flg=0x80000 pkg=com.android.vending }
~~~

**Comment by barbeau** [comment] 2015-10-30 22:15
Thanks for the report @ssypi!  If I get you an APK with a fix, would you be able to test and confirm?

**Comment by ssypi** [comment] 2015-10-30 23:30
I can do that, but most likely it also happens on standard android emulator as well which should let you test it.

**Comment by barbeau** [comment] 2015-11-05 22:39
Yup, I can reproduce this on the emulator.

**Comment by barbeau** [comment] 2015-11-05 23:04
Fixed in `develop` via https://github.com/OneBusAway/onebusaway-android/commit/115fab736c74a1796af4b23f2609bcccf68725a4.

Note that after you get the message about the Play Store not being installed, you'll still see this:

![image](https://cloud.githubusercontent.com/assets/928045/10984436/77122dba-83e7-11e5-9f36-20a2daf4ab17.png)

...and if you click on that button, you'll see the same crash.  That crash we can't do anything about, as that button is baked into the SupportMapFragment and shows up when Google Maps isn't available.

@ssypi Let me know if you have any suggestions for a better message in the case where Play Store isn't installed.  I'm currently assuming the user pretty has to start Googling and take it from there.

**Closed by barbeau** 2015-11-05 23:04 UTC
Labels: bug

**Comment by bbodenmiller** [comment] 2015-11-15 13:13
I'm having a similar issue in the emulator:
![image](https://cloud.githubusercontent.com/assets/1192780/11168862/1031a8c4-8b57-11e5-87df-0681ce3a91c9.png)

Selecting Update results in a crash:
![image](https://cloud.githubusercontent.com/assets/1192780/11168866/25cdecec-8b57-11e5-8bb8-1a8c74aa093e.png)

Google Maps seems to be running fine on the emulator:
![image](https://cloud.githubusercontent.com/assets/1192780/11168873/984a2e34-8b57-11e5-89f6-54d8c8d01b3e.png)

Ideas?

**Comment by barbeau** [comment] 2015-11-15 21:08
Are you using an emulator (AVD) for the Google APIs?  Each API level has at
least two emulator versions - one for the basic API level, and one for the
Google APIs.  To use Google Play Services in the emulator you need to be
running an AVD for Google APIs.  That should probably be in the Readme if
it isn't currently.

We can't control the crash when you click on the button in that form - its
baked into the SupportMapFragment, which is part of the Google support
library.  So its actually a Google issue.

**Comment by bbodenmiller** [comment] 2015-11-16 05:39
I will have to check. Shouldn't Google Maps only be installed in the emulator with Google APIs?

**Comment by barbeau** [comment] 2015-11-16 15:42
>Shouldn't Google Maps only be installed in the emulator with Google APIs?

Not sure, I haven't looked.

**Comment by bbodenmiller** [comment] 2015-11-25 07:45
Unfortunately still no luck:

![image](https://cloud.githubusercontent.com/assets/1192780/11390403/a375a7f8-92fe-11e5-9fc1-f06c06936e9f.png)

![image](https://cloud.githubusercontent.com/assets/1192780/11390411/b8485090-92fe-11e5-8911-330e6563cad6.png)

Here lies the problem... the latest image does not have the latest Play Services nor auto update:

![image](https://cloud.githubusercontent.com/assets/1192780/11390747/ceb10716-9301-11e5-95bc-34e95011c1a8.png)

**Comment by barbeau** [comment] 2015-11-25 14:13
Try using an AVD based on API 21 Google APIs.  The API 22 and 23 emulators have a number of open AOSP bugs - I believe you're seeing [this bug](https://code.google.com/p/android/issues/detail?id=176348&thanks=176348&ts=1433887196).
