### ISSUE TITLE
Nearby view does not auto center on location

### ISSUE THREAD

**Issue by bbodenmiller** [OneBusAway/onebusaway-android#579] opened 2016-07-05 16:12 UTC
**Summary:** 

When I select the nearby view I expect it to show stops near my current location but instead it just shows the last location I viewed

**Steps to reproduce:** 

1. Open app
2. Select nearby
3. Pan to random location
4. Close app by removing from recent apps view
5. Open app

**Expected behavior:** 

When nearby view is opened, show nearby stops to current user location

**Observed behavior:** 

Observe map in random location when nearby view opened

**Device and Android version:** 

Nexus 5X, OBA 2.0.14 (64)

**Screenshots:** 

N/A

**Comment by barbeau** [comment] 2016-07-05 16:25
So this is actually working as intended, after fixing https://github.com/OneBusAway/onebusaway-android/issues/551, via PR https://github.com/OneBusAway/onebusaway-android/pull/557.

We now always show the previous map view when returning to the app and the Nearby screen.  To re-center map on your location, you just need to hit the "My location" button.  This behavior is the same as Google Maps.

Reason for the change is that we've gotten a lot of complaints about map behavior when location services are off  - Maps API default behavior changed from Maps API v1 to v2 - v2 auto-recenters over 0,0, where as Maps v1 automatically remembered your last map view).  Therefore we need to auto-position the map without relying on location.  If we do that, but also try to re-center on location when it's available, it creates some erratic behavior.

I'm open to reexamining this behavior, but I'd need to hear complaints from a number of users that the same behavior as Google Maps isn't working for them in OBA.

**Comment by bbodenmiller** [comment] 2016-07-05 16:59
From https://github.com/OneBusAway/onebusaway-android/pull/557:

> now, the map will automatically be restored to the previous map center and zoom, even if location services are available. Previously, if location services were turned on and available, the map would always center on the user's location. IMHO this new behavior is correct - it matches the behavior of Google Maps. If the user wants to re-center the map on their location, they can just hit the "My Location" floating action button.

The implementation in OBA seems to be slightly different than Google Maps. In Google Maps if you have the follow location button tapped it will follow your location and bring you to your current location on app launch (if you did not have the button selected then it brings you to the last viewed area like OBA). With OBA it appears it does not matter if you recently selected the location button, it always restores the map to the last viewed location. I like Google Maps implementation better.

Also worth noting Google Maps location button follows the user location whereas OBA does not (https://github.com/OneBusAway/onebusaway-android/issues/372).

**Comment by barbeau** [comment] 2016-07-05 18:07
@bbodenmiller You're correct, Google Maps does have a "follow mode", which you can trigger by tapping on the "My location" button and then not touching the map.  When the cross-hairs has a blue hue (vs. the normal gray), it means that "follow mode" is activated:

![image](https://cloud.githubusercontent.com/assets/928045/16594669/76342862-42b9-11e6-95d0-aadaa603e817.png)

I agree that if we implement a follow-mode, we should have the map re-open to the user's real-time location instead of the previous map view - I added a comment on this in https://github.com/OneBusAway/onebusaway-android/issues/372#issuecomment-230556037.

**Comment by barbeau** [comment] 2016-07-07 19:58
I'm reopening this, as I have heard from a few users that miss the auto-recenter:

>* Why doesn't the new app find my current location ?

>* The app use to work fine, but now with the new update, the app can't find my location, and the screen doesn't even move to your location like it use to.

>* I never had to add my location before it just popped up now it is all messed up

I'll look at implementing an initial zoom to location if location exists, and otherwise using the previous map bounds, and try to make sure they don't fight one another.

**Comment by barbeau** [comment] 2016-07-07 20:10
We should probably add a preference for re-centering on location as well, so if someone doesn't want it always snapping to their real-time position and wants it to remain fixed on their previous map view they can disable the real-time location snapping.

**Comment by barbeau** [comment] 2016-07-11 15:37
On second thought, let's leave out the preference for now, unless users really voice a need for this.  I'd like to keep the number of preferences small, which let's users easily see what's available to change, and also avoids them accidentally changing something that could break some of the expected behavior.

**Comment by barbeau** [comment] 2016-07-13 20:05
While working on this, I also noticed that in `BaseMapFragment.setMyLocation()`, we weren't injecting the `GoogleApiClient` in `Application.getLastKnownLocation()` so the fused location provide location could be considered as a possible real-time position used to center the map when the use taps on the "My Location" button.  I changed this to inject the `GoogleApiClient`, so hopefully this helps center the map on the user's location in instances where the fused provide has a last known location but the GPS and NETWORK providers don't.

**Comment by barbeau** [comment] 2016-07-27 01:12
I'm reopening this - it's appears that when auto-centering on location, we're using the previously saved zoom level.  That wasn't my intent - we should be using the default zoom level.

**Closed** 2016-07-28 20:09 UTC
Labels: bug
